=== MateSandor/AQUSP7_XMLGyak/XMLTaskAQUSP7/XMLSchemaAQUSP7.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Emag">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="Cim">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="iranyitoszam" type="xs:integer" />
                            <xs:element name="varos" type="xs:string" />
                            <xs:element name="utca" type="xs:string" />
                            <xs:element name="hazszam" type="xs:integer" />
                        </xs:sequence>
                        <xs:attribute name="Cid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="Gyarto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ertekeles" type="xs:integer" />
                            <xs:element name="gyartonev" type="xs:string" />
                            <xs:element name="elerhetosegek" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="Gyid" type="xs:string" use="required" />
                        <xs:attribute name="FTid" type="xs:string" use="required" />
                        <xs:attribute name="FCid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="Termek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="termeknev" type="xs:string" />
                            <xs:element name="tipus" type="xs:string" />
                            <xs:element name="egysegar" type="xs:integer" />
                        </xs:sequence>
                        <xs:attribute name="Tid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="Tartalmazza">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="darab" type="xs:integer" />
                        </xs:sequence>
                        <xs:attribute name="Taid" type="xs:string" use="required" />
                        <xs:attribute name="FTid" type="xs:string" use="required" />
                        <xs:attribute name="FRid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="Rendeles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="osszertek" type="xs:string" nillable="true"/>
                            <xs:element name="datum">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ev" type="xs:integer" />
                                        <xs:element name="honap" type="xs:integer" />
                                        <xs:element name="nap" type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Rid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="Vevo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pontok" type="xs:integer" />
                        </xs:sequence>
                        <xs:attribute name="Vid" type="xs:string" use="required" />
                        <xs:attribute name="FNid" type="xs:string" use="required" />
                        <xs:attribute name="FCid" type="xs:string" use="required" />
                        <xs:attribute name="FRid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="Nev">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="vezeteknev" type="xs:string" />
                            <xs:element name="keresztnev" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="Nid" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
		
		<!-- Kulcsok-->

		<xs:key name="Cid">
            <xs:selector xpath="Cim" />
            <xs:field xpath="@Cid" />
        </xs:key>

        <xs:key name="Gyid">
            <xs:selector xpath="Gyarto" />
            <xs:field xpath="@Gyid" />
        </xs:key>

        <xs:key name="Tid">
            <xs:selector xpath="Termek" />
            <xs:field xpath="@nev" />
        </xs:key>

        <xs:key name="Taid">
            <xs:selector xpath="Tartalmazza" />
            <xs:field xpath="@Taid" />
        </xs:key>

        <xs:key name="Vid">
            <xs:selector xpath="Vevo" />
            <xs:field xpath="@Vid" />
        </xs:key>

        <xs:key name="Nid">
            <xs:selector xpath="Nev" />
            <xs:field xpath="@Nid" />
        </xs:key>
        
        <!-- Idegen kulcsok -->

        <xs:keyref refer="Cid" name="Cim_idegen_kulcs">
            <xs:selector xpath="Rendeles" />
            <xs:field xpath="@FCid" />
        </xs:keyref>

        <xs:keyref refer="Gyid" name="Gyarto_idegen_kulcs">
            <xs:selector xpath="Rendeles" />
            <xs:field xpath="@FGyid" />
        </xs:keyref>

        <xs:keyref refer="Tid" name="Termek_Cim_idegen_kulcs">
            <xs:selector xpath="Cim" />
            <xs:field xpath="@FTid" />
        </xs:keyref>

        <xs:keyref refer="Cid" name="Cim_Tartalmazza_idegen_kulcs">
            <xs:selector xpath="Tartalmazza" />
            <xs:field xpath="@FCid" />
        </xs:keyref>

        <xs:keyref refer="Gyid" name="Gyarto_Tartalmazza_idegen_kulcs">
            <xs:selector xpath="Tartalmazza" />
            <xs:field xpath="@FGyid" />
        </xs:keyref>
		
    </xs:element>
</xs:schema>

=== MateSandor/AQUSP7_XMLGyak/XMLTaskAQUSP7/DomParseAQUSP7/XMLAQUSP7.xml
<?xml version="1.0" encoding="UTF-8"?>

<Emag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="XMLSchemaAQUSP7.xsd">

    <!-- Cimek-->
    <Cim Cid="c1">
        <iranyitoszam>3720</iranyitoszam>
        <varos>Sajokaza</varos>
        <utca>Majus 1 ut</utca>
        <hazszam>11</hazszam>
    </Cim>

    <Cim Cid="c2">
        <iranyitoszam>3720</iranyitoszam>
        <varos>Sajoivanka</varos>
        <utca>Petofi Sandor</utca>
        <hazszam>2</hazszam>
    </Cim>

    <Cim Cid="c3">
        <iranyitoszam>3700</iranyitoszam>
        <varos>Kazincbarcika</varos>
        <utca>Majus 1 ut</utca>
        <hazszam>3</hazszam>
    </Cim>

    <Cim Cid="c4">
        <iranyitoszam>3530</iranyitoszam>
        <varos>Miskolc</varos>
        <utca>Szent istvan</utca>
        <hazszam>47</hazszam>
    </Cim>

    <Cim Cid="c5">
        <iranyitoszam>3530</iranyitoszam>
        <varos>Miskolc</varos>
        <utca>Joyson utca</utca>
        <hazszam>1</hazszam>
    </Cim>

    <!-- Gyartok-->
    <Gyarto Gyid="gy1" FGyTid="t1" FGyCid="c4">
        <ertekeles>5</ertekeles>
        <gyartonev>Makita</gyartonev>
        <elerhetosegek>Makita.eu</elerhetosegek>
    </Gyarto>

    <Gyarto Gyid="gy2" FGyTid="t2" FGyCid="c5">
        <ertekeles>2</ertekeles>
        <gyartonev>LaptopShop</gyartonev>
        <elerhetosegek></elerhetosegek>
    </Gyarto>

    <Gyarto Gyid="gy3" FGyTid="t3" FGyCid="c2">
        <ertekeles>4</ertekeles>
        <gyartonev>Ikea</gyartonev>
        <elerhetosegek>Ikea.com</elerhetosegek>
    </Gyarto>

    <!-- Termekek-->
    <Termek Tid="t1">
        <termeknev>Elektromos funyiro</termeknev>
        <tipus>Elektronika</tipus>
        <egysegar>70000</egysegar>
    </Termek>

    <Termek Tid="t2">
        <termeknev>Thinkpad T450</termeknev>
        <tipus>Elektronika</tipus>
        <egysegar>200000</egysegar>
    </Termek>

    <Termek Tid="t3">
        <termeknev>Skorgjorn parna</termeknev>
        <tipus>Butor</tipus>
        <egysegar>8000</egysegar>
    </Termek>

    <!-- Tartalmazza-->
    <Tartalmazza Taid="t1" FTaTid="t1" FTaRid="r1">
        <darab>1</darab>
    </Tartalmazza>

    <Tartalmazza Taid="t2" FTaTid="t2" FTaRid="r2">
        <darab>2</darab>
    </Tartalmazza>

    <Tartalmazza Taid="t3" FTaTid="t3" FTaRid="r3">
        <darab>1</darab>
    </Tartalmazza>

    <!-- Rendelesek-->
    <Rendeles Rid="r1">
        <osszertek>270000</osszertek>
        <datum>
            <ev>2022</ev>
            <honap>11</honap>
            <nap>22</nap>
        </datum>
    </Rendeles>

    <Rendeles Rid="r2">
        <osszertek></osszertek>
        <datum>
            <ev>2022</ev>
            <honap>10</honap>
            <nap>5</nap>
        </datum>
    </Rendeles>

    <Rendeles Rid="r3">
        <osszertek></osszertek>
        <datum>
            <ev>2021</ev>
            <honap>12</honap>
            <nap>21</nap>
        </datum>
    </Rendeles>

    <!-- Vevok-->
    <Vevo Vid="v1" FVeNid="n1" FVeCid="c1" FVeRid="r1">
		<felnott>Igen</felnott>
        <pontok>110</pontok>
    </Vevo>

    <Vevo Vid="v2" FVeNid="n2" FVeCid="c2" FVeRid="r2">
		<felnott>Nem</felnott>
        <pontok>0</pontok>
    </Vevo>

    <Vevo Vid="v3" FVeNid ="n3" FVeCid="c3" FVeRid="r3">
		<felnott>Igen</felnott>
        <pontok>10</pontok>
    </Vevo>

    <!-- Nevek-->
    <Nev Nid="n1">
        <vezeteknev>Sandor</vezeteknev>
        <keresztnev>Mate</keresztnev>
    </Nev>

    <Nev Nid="n2">
        <vezeteknev>Joska</vezeteknev>
        <keresztnev>Gyurka</keresztnev>
    </Nev>

    <Nev Nid="n3">
        <vezeteknev>Gabor</vezeteknev>
        <keresztnev>Aron</keresztnev>
    </Nev>


</Emag>

=== MateSandor/AQUSP7_XMLGyak/XMLTaskAQUSP7/XMLAQUSP7.xml
<?xml version="1.0" encoding="UTF-8"?>

<Emag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="XMLSchemaAQUSP7.xsd">

    <!-- Cimek-->
    <Cim Cid="c1">
        <iranyitoszam>3720</iranyitoszam>
        <varos>Sajokaza</varos>
        <utca>Majus 1 út</utca>
        <hazszam>11</hazszam>
    </Cim>

    <Cim Cid="c2">
        <iranyitoszam>3720</iranyitoszam>
        <varos>Sajoivanka</varos>
        <utca>Petofi Sandor</utca>
        <hazszam>2</hazszam>
    </Cim>

    <Cim Cid="c3">
        <iranyitoszam>3700</iranyitoszam>
        <varos>Kazincbarcika</varos>
        <utca>Majus 1 út</utca>
        <hazszam>3</hazszam>
    </Cim>

    <Cim Cid="c4">
        <iranyitoszam>3530</iranyitoszam>
        <varos>Miskolc</varos>
        <utca>Szent istvan</utca>
        <hazszam>47</hazszam>
    </Cim>

    <Cim Cid="c5">
        <iranyitoszam>3530</iranyitoszam>
        <varos>Miskolc</varos>
        <utca>Joyson utca</utca>
        <hazszam>1</hazszam>
    </Cim>

    <!-- Gyartok-->
    <Gyarto Gyid="gy1" FTid="t1" FCid="c4">
        <ertekeles>5</ertekeles>
        <gyartonev>Makita</gyartonev>
        <elerhetosegek>Makita.eu</elerhetosegek>
    </Gyarto>

    <Gyarto Gyid="gy2" FTid="t2" FCid="c5">
        <ertekeles>2</ertekeles>
        <gyartonev>LaptopShop</gyartonev>
        <elerhetosegek>+36702682881</elerhetosegek>
    </Gyarto>

    <Gyarto Gyid="gy3" FTid="t3" FCid="c2">
        <ertekeles>4</ertekeles>
        <gyartonev>Ikea</gyartonev>
        <elerhetosegek>Ikea.com</elerhetosegek>
    </Gyarto>

    <!-- Termékek-->
    <Termek Tid="t1">
        <termeknev>Elektromos funyíro</termeknev>
        <tipus>Elektronika</tipus>
        <egysegar>70000</egysegar>
    </Termek>

    <Termek Tid="t2">
        <termeknev>Thinkpad T450</termeknev>
        <tipus>Elektronika</tipus>
        <egysegar>200000</egysegar>
    </Termek>

    <Termek Tid="t3">
        <termeknev>Skorgjorn parna</termeknev>
        <tipus>Butor</tipus>
        <egysegar>8000</egysegar>
    </Termek>

    <!-- Tartalmazza-->
    <Tartalmazza Taid="t1" FTid="t1" FRid="r1">
        <darab>1</darab>
    </Tartalmazza>

    <Tartalmazza Taid="t2" FTid="t2" FRid="r2">
        <darab>2</darab>
    </Tartalmazza>

    <Tartalmazza Taid="t3" FTid="t3" FRid="r3">
        <darab>1</darab>
    </Tartalmazza>

    <!-- Rendelesek-->
    <Rendeles Rid="r1">
        <osszertek>270000</osszertek>
        <datum>
            <ev>2022</ev>
            <honap>11</honap>
            <nap>22</nap>
        </datum>
    </Rendeles>

    <Rendeles Rid="r2">
        <osszertek></osszertek>
        <datum>
            <ev>2022</ev>
            <honap>10</honap>
            <nap>5</nap>
        </datum>
    </Rendeles>

    <Rendeles Rid="r3">
        <osszertek></osszertek>
        <datum>
            <ev>2021</ev>
            <honap>12</honap>
            <nap>21</nap>
        </datum>
    </Rendeles>

    <!-- Vevok-->
    <Vevo Vid="v1" FNid="n1" FCid="c1" FRid="r1">
        <pontok>110</pontok>
    </Vevo>

    <Vevo Vid="v2" FNid="n2" FCid="c2" FRid="r2">
        <pontok>0</pontok>
    </Vevo>

    <Vevo Vid="v3" FNid ="n3" FCid="c3" FRid="r3">
        <pontok>10</pontok>
    </Vevo>

    <!-- Nevek-->
    <Nev Nid="n1">
        <vezeteknev>Sandor</vezeteknev>
        <keresztnev>Mate</keresztnev>
    </Nev>

    <Nev Nid="n2">
        <vezeteknev>Joska</vezeteknev>
        <keresztnev>Gyurka</keresztnev>
    </Nev>

    <Nev Nid="n3">
        <vezeteknev>Gabor</vezeteknev>
        <keresztnev>Aron</keresztnev>
    </Nev>


</Emag>
